describe('console.error', () => {
  it('does not throw', () => {
    // Expected to be empty as we want to ensure the test works with a call outside of tests
    // and not something that happens during testing.
  })
})
